djproject/home/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.resolvers import URLPattern
from home import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index, name="index"),
    path("complain_Rec", views.complain_Rec, name="complain_Rec"),
    path("ad_123_3360", views.ad_123_3360, name="nead_123_3360"),
    path("/login_user", views.login_user, name="login_user"),
    path("adminhome", views.adminhome, name="adminhome"),
    path("delete/<int:id>/", views.delete, name="delete"),
    path("update/<int:id>/", views.update, name="update"),
    path("addrecord", views.addrecord, name="addrecord"),
    path("suspect_records", views.suspect_records, name="suspect_records"),
    path("workforce", views.workforce, name="workforce"),
    path("criminals", views.criminals, name="criminals"),
    path("prisoners", views.prisoners, name="prisoners"),
    path("designations", views.designations, name="designations"),
    path("logoutuser", views.logoutuser, name="logoutuser"),
    path("addcase", views.addcase, name="addcase"),
    path("addofficer", views.addofficer, name="addofficer"),
    path("addsuspect", views.addsuspect, name="addsuspect"),
    path("cases", views.cases, name="cases"),
    path("deletecase/<int:id>/", views.deletecase, name="deletecase"),
    path("delete_criminal/<int:id>/", views.delete_criminal, name="delete_criminal"),
    path("deleteofficer/<int:id>/", views.deleteofficer, name="deleteofficer"),
    path("updatecase/<int:id>/", views.updatecase, name="updatecase"),
    path("addcriminal", views.addcriminal, name="addcriminal"),
    path("update_criminal/<int:id>/", views.update_criminal, name="update_criminal"),
    path("updateofficer/<int:id>/", views.updateofficer, name="updateofficer"),
    path("update_prisoner/<int:id>/", views.update_prisoner, name="update_prisoner"),
    path("updatesuspect/<str:id>/", views.updatesuspect, name="updatesuspect"),
    path("deletesuspect/<str:id>/", views.deletesuspect, name="deletesuspect"),
    path("delete_prisoner/<int:id>/", views.delete_prisoner, name="delete_prisoner"),
    path("cases_csv", views.cases_csv, name="cases_csv"),
    path("complainrecords_csv", views.complainrecords_csv, name="complainrecords_csv"),
    path("workforce_csv", views.workforce_csv, name="workforce_csv"),
    path("suspects_csv", views.suspects_csv, name="suspects_csv"),
    path("criminals_csv", views.criminals_csv, name="criminals_csv"),
    path("add_desig", views.add_desig, name="add_desig"),
    path("update_desg/<str:id>/", views.update_desg, name="update_desg"),
    path("designations_csv", views.designations_csv, name="designations_csv"),
    path("prisoners_csv", views.prisoners_csv, name="prisoners_csv"),
    path("addprisoner", views.addprisoner, name="addprisoner"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

djproject/myuserapp/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path("admin/", admin.site.urls),
    url(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    url(r"^static/(?P<path>.*)$", serve, {"document_root": settings.STATIC_ROOT}),
    path("", views.index),
    path("complain_Rec", views.complain_Rec),
    path("ad_123_3360", views.ad_123_3360),
    path("api-auth/", include("rest_framework.urls")),
    path("login_user", views.login_user),
    path("adminhome", views.adminhome),
    path("", include("django.contrib.auth.urls")),
    path("delete/<int:id>/", views.delete),
    path("update/<int:id>/", views.update),
    path("addrecord", views.addrecord),
    path("suspect_records", views.suspect_records),
    path("workforce", views.workforce),
    path("criminals", views.criminals),
    path("logoutuser", views.logoutuser),
    path("addcase", views.addcase),
    path("addofficer", views.addofficer),
    path("addsuspect", views.addsuspect),
    path("cases", views.cases),
    path("prisoners", views.prisoners),
    path("deletecase/<int:id>/", views.deletecase),
    path("delete_criminal/<int:id>/", views.delete_criminal),
    path("updatecase/<int:id>/", views.updatecase),
    path("addcriminal", views.addcriminal),
    path("complainrecords_csv", views.complainrecords_csv),
    path("update_criminal/<int:id>/", views.update_criminal),
    path("updateofficer/<str:id>/", views.updateofficer),
    path("updatesuspect/<str:id>/", views.updatesuspect),
    path("deletesuspect/<str:id>/", views.deletesuspect),
    path("deleteofficer/<int:id>/", views.deleteofficer),
    path("delete_prisoner/<int:id>/", views.delete_prisoner),
    path("complainrecords_csv", views.complainrecords_csv),
    path("workforce_csv", views.workforce_csv),
    path("cases_csv", views.cases_csv),
    path("suspects_csv", views.suspects_csv),
    path("criminals_csv", views.criminals_csv),
    path("update_prisoner/<int:id>/", views.update_prisoner),
    path("designations", views.designations),
    path("add_desig", views.add_desig),
    path("update_desg/<str:id>/", views.update_desg),
    path("delete_desig/<str:id>/", views.delete_desig),
    path("designations_csv", views.designations_csv),
    path("prisoners_csv", views.prisoners_csv),
    path("addprisoner", views.addprisoner),
]

djproject/home/models.py
from django.db import models
from django.db.models.expressions import Value
from django.db.models.fields.related import ForeignKey
from django.db.models.constraints import UniqueConstraint
from django.db.models.deletion import CASCADE
from django.db.models.expressions import Value


# Create your models here.


class ComplainReg(models.Model):
    complain_id = models.AutoField(primary_key=True)
    complainee_fname = models.CharField(max_length=20)
    complainee_lname = models.CharField(max_length=20)
    dateofcomplain = models.DateField()
    timeofcomplain = models.TimeField()
    complainee_cnic = models.CharField(max_length=15)
    complainee_contactno = models.CharField(max_length=11)
    FIR_status = models.BooleanField(default=0)
    crime_description = models.TextField(max_length=200)
    victim_description = models.TextField(max_length=150)
    email_address = models.EmailField(max_length=25)


class Designations(models.Model):

    BasicSalary = models.IntegerField()
    Designation = models.CharField(max_length=30, unique=True)
    Ranking = models.IntegerField(primary_key=True)


class Work_force(models.Model):
    
    
    officer = models.AutoField(primary_key=True)
    Officerfname = models.CharField(max_length=20)
    Officerlname = models.CharField(max_length=20)
    Officer_CNIC = models.CharField(max_length=15, unique=True)
    Officer_email = models.CharField(max_length=25)
    Officer_cellNo = models.BigIntegerField()
    Officer_phoneNo = models.CharField(max_length=11)
    Officer_DOB = models.DateField()
    Officer_DOJ = models.DateField()
    Officer_Education = models.CharField(max_length=27)
    Temp_address = models.CharField(max_length=70)
    Permanent_address = models.CharField(max_length=70)
    MaritalStatus = models.CharField(max_length=10)
    PostingNo = models.IntegerField()
    Ranking = models.ForeignKey(Designations, on_delete=CASCADE)


class CasesRecord(models.Model):
    
    
    case_id = models.AutoField(primary_key=True)
    complain_id = models.OneToOneField(ComplainReg, on_delete=CASCADE)
    officer = models.ForeignKey(Work_force, on_delete=CASCADE, default=None)
    CrimeScene = models.CharField(max_length=50)
    Evidence = models.CharField(max_length=50)
    CaseStatus = models.BooleanField(default=0)


class SuspectRecord(models.Model):

    CNIC = models.CharField(primary_key=True, unique=True, max_length=15)

    suspectlFname = models.CharField(max_length=20)
    suspectLname = models.CharField(max_length=20)
    suspect_DOB = models.DateField(blank=True, null=False)
    Height = models.CharField(max_length=6)
    Education = models.CharField(max_length=20)
    BloodGroup = models.CharField(max_length=6)
    address = models.CharField(max_length=60)
    MaritalStatus = models.CharField(max_length=10)
    Picture = models.ImageField(blank=True)


class CriminalRecord(models.Model):
    

    criminal_ID = models.AutoField(primary_key=True)
    CNIC = models.ForeignKey(SuspectRecord, on_delete=CASCADE)
    case_id = ForeignKey(CasesRecord, on_delete=CASCADE)
    Sentence = models.CharField(max_length=25)
    CaptureStatus = models.BooleanField()


class PrisonerRecord(models.Model):
    
    
    Prisoner_id = models.AutoField(primary_key=True)
    criminal_ID = models.ForeignKey(CriminalRecord, on_delete=CASCADE)
    DateOfTransfer = models.DateField()
    TimeOftransfer = models.TimeField()
    JailClass = models.CharField(max_length=6)
    TransferStatus = models.BooleanField(default=0)

djproject/templates/adminhomepage.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin home</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">


    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    {%load static%}
    <link rel="stylesheet" href="{% static "adminhomecss.css" %}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand">Criminal Database</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <form class="navitems d-flex" method="post" action="/logoutuser">
                {% csrf_token %}
                
                    <button class=" btn btn-outline-success" type="submit">logout</button>
                </form>
            </div>
        </div>
    </nav>

    <div class="maincontainer">

        <div class="col inrow">
            <div class="card shadow-sm">
                <header class="cardhead">
                    <h5>
                        Complain Records</h5>
                    <i class="fas fa-paste"></i>
                </header>
                <div class="card-body">

                    <p class="card-text"></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="/complain_Rec" target=_blank><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>
                            
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>

        <div class="col inrow">
            <div class="card shadow-sm">
                <header class="cardhead">
                    <h5>
                        Cases Records</h5>

                    <i class="fas fa-paste"></i>
                </header>
                <div class="card-body">
                    <p class="card-text"></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                           <a href="/cases" target=_blank><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>
                            
                        </div>
                       
                    </div>
                </div>
            </div>
        </div>

        <div class="col inrow">
            <div class="card shadow-sm">
                <header class="cardhead">
                    <h5>
                        Criminal Records</h5>

                    <i class="fas fa-paste"></i>
                </header>
                <div class="card-body">
                    <p class="card-text"></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="/criminals"target=_blank><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>
                          
                        </div>
                      
                    </div>
                </div>
            </div>
        </div>

        <div class="col inrow">
            <div class="card shadow-sm">
                <header class="cardhead">
                    <h5>Workforce Records</h5>

                    <i class="fas fa-paste"></i>
                </header>
                <div class="card-body">
                    <p class="card-text"></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="/workforce" target=_blank><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>
                          
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col inrow">
            <div class="card shadow-sm">
                <header class="cardhead">
                    <h5>Suspect Records</h5>

                    <i class="fas fa-paste"></i>
                </header>
                <div class="card-body">
                    <p class="card-text"></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                           <a href="/suspect_records" target=_blank><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>
                          
                        </div>
                
                    </div>
                </div>
            </div>
        </div>
        <div class="col inrow">
            <div class="card shadow-sm">
                <header class="cardhead">
                    <h5>Prisoner Records</h5>

                    <i class="fas fa-paste"></i>
                </header>
                <div class="card-body">
                    <p class="card-text"></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                           <a href="/prisoners" target=_blank><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>
                          
                        </div>
             
                    </div>
                </div>
            </div>
        </div>
        <div class="col inrow">
            <div class="card shadow-sm">
                <header class="cardhead">
                    <h5>Designations</h5>

                    <i class="fas fa-paste"></i>
                </header>
                <div class="card-body">
                    <p class="card-text"></p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                           <a href="/designations" target=_blank><button type="button" class="btn btn-sm btn-outline-secondary">View</button></a>
                          
                        </div>
             
                    </div>
                </div>
            </div>
        </div>





    </div>





</body>

</html>

djproject/templates/casesrecord.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cases</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">


    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    {% load static %}
    <link rel="stylesheet" href="{% static "comrecords.css" %}">
    <link rel="stylesheet" href="{% static "popupwindow.css" %}">
    <link rel="stylesheet" href="{% static "toast.css" %}">
    <style>
        .popup .contents {
            position: absolute;
            border-radius: 7px;
            top: 34%;
            left: 50%;
            transform: translate(-50%, -50%) scale(0);
            background: #fff;
            width: 50%;
            max-width: 430px;
            height: 378px;
            z-index: 2;
            /* text-align: center; */
            padding: 20px;
            box-sizing: border-box;
        }
    </style>


</head>

<body>

    {%if messages %}
    {% for message in messages %}
    <div id="msgg" class="msg alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        <strong> {{message}}</strong>
        <button id="CLOSE" type="button" onclick="closeWin()" class="clss btn-close" data-bs-dismiss="alert"
            aria-label="Close"></button>

    </div>
    {%endfor%}
    {%endif%}
    <header>
        <h2 class="container">Cases Records</h2>
        <hr>

    </header>

    <p class="report">Reported Generated on: <span id="time"></span></p>

    <div id="snackbar">Record Deleted successfully</div>

    <!--button for adding new record-->
    <button class="add" onclick="togglePopup2()"> Add New Record <i class="px-1 fas fa-pencil-alt"></i></button>

    <a href="/cases_csv">
        <button class="download"> Download Records<i class="fas fa-download"></i></button>
    </a>

    <!--popup window for adding new record-->
    <div class="popup" id="popup-2">
        <div class="overlay"></div>
        <div class="contents">
            <div class="close-btn" onclick="togglePopup2()">×</div>
            <h4>Add New Record</h4>
            <hr>
            <form autocomplete="off" method="post" action="/addcase">
                <input type="hidden" autocomplete="False" name="" id="">
                {% csrf_token %}
                <input type='number' class="input-field" placeholder="Complain ID" name='complain_id' required>

                <input type='text' class='input-field' placeholder="Crime Scene" required name='CrimeScene'>

                <input type='text' class='input-field' placeholder="Evidences" required name='Evidence'>

                <input type='number' class='input-field' placeholder="Case Status" required name='CaseStatus'>


                <input type='number' class='input-field' placeholder="Assigned Officer" required name='officer'>

                <button type="submit" class="btn btn-primary save">Save
                    Changes</button>
            </form>
            <a><button class="dontsave btn btn-primary" onclick="togglePopup2()">Cancel</button></a>

        </div>
    </div>


    <!--table start-->
    <div class="tbrow">

        <div class="col-md-12">
            <table class='table-hover table'>
                <thead class='tablehead'>
                    <tr>
                        <th class="column">Complian ID</th>
                        <th class="column">Case ID</th>
                        <th class="column">Case Status</th>
                        <th class="column">Crime Scene</th>
                        <th class="column">Evidences </th>
                        <th class="column">Assigned Officer ID</th>

                    </tr>
                </thead>

                <tbody>
                    {% for i in cases %}
                    <tr class="rows">

                        <td>{{i.complain_id_id}}</td>
                        <td>{{i.case_id}}</td>
                        {% if i.CaseStatus == True %}
                        <td>solved</td>
                        {%else%}
                        <td>Unsolved</td>
                        {%endif%}

                        <td>{{i.CrimeScene}}</td>
                        <td>{{i.Evidence}}</td>
                        <td>{{i.officer_id}}</td>

                        <td class="del">
                            <a onclick="myFunction()" href="deletecase/{{i.case_id}}"><button type="button"
                                    class="btn btn-success">Delete</button>
                            </a>

                            {% comment %} a href="/product/?parameter={{ product.name }}
                            &parameter_1={{ product.price }}&parameter_2={{ product.time }}" {% endcomment %}

                            <a href="updatecase/{{i.case_id}}"><button type="button"
                                    class="btn btn-success">Update</button></a>
                        </td>
                        {%endfor%}
                    </tr>

                </tbody>
            </table>

        </div>

    </div>

    <script>
        function closeWin() {

            let b = document.getElementById("msgg");
            b.style.display = "none"

        }

        function togglePopup() {
            document.getElementById("popup-1").classList.toggle("active");
        }

        function togglePopup2() {
            document.getElementById("popup-2").classList.toggle("active");
        }

        function myFunction() {

            var x = document.getElementById("snackbar");
            x.className = "show";
            setTimeout(function () {
                x.className = x.className.replace("show", "");
            }, 3000);
        }

        var today = new Date();

        var date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();

        var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();

        var dateTime = date + ' ' + time;
        document.getElementById("time").innerHTML = dateTime;
    </script>
</body>

</html>

djproject/templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>



    {% load static %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>

    <link rel="stylesheet" href="{% static "logincss.css" %}">
    <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">

</head>


<body>
    <nav>
        <h5>Login Into Database</h5>
    </nav>

    {%if messages %}
    {% for message in messages %}
    <div class="msg alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
        <strong> {{message}}</strong>
        <button type="button" class="clss btn-close" data-bs-dismiss="alert" aria-label="Close">X</button>

    </div>
    {%endfor%}
    {%endif%}

    <div class="container">

        <header>
            <h3>Police Database</h3>
        </header>
         <form autocomplete="off" action="/login_user" method="post">
            <input type="hidden" autocomplete="False" name="" id="">
            {% csrf_token %}
            <label for="username">Username: </label>
            <input  type="text" name="username" id="username" placeholder="username" required>

            <label for="passsword">Password: </label>
            <input  type="Password" name="password" id="password" placeholder="password" required>

            <button id="submitbutton" type="submit">Login</button>
        </form>

    </div>

</body>

</html>

djproject/templates/update.html
{%load widget_tweaks%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>



    <style>
        .form-group {
            position: absolute;

            display: inline-block;
            width: 411px;

            padding: 10px;
            left: 10%;
        }

        .heads {
            margin-top: 23px;
            margin-left: 20px;
            font-size: calc(1.3rem + .6vw);
        }

        button,
        input,
        optgroup,
        select,
        textarea {
            margin: 10px;
            width: 100%;
            border-radius: 4px;
            border: 1px solid black;
            font-family: monospace;
            font-size: 17px;
            display: flex;
            padding: 3px;
        }

        label {
            display: inline-block;
            font-weight: bold;
            font-size: 17px;
        }


        .btn-primary {
            color: #fff;
            width: 157px;
            font-size: 18px;
            position: absolute;
            bottom: -50px;
            font-family: system-ui;
            background-color: #0d6efd;
            border-color: #0d6efd;
        }


        #id_FIR_status {
            position: absolute;
            bottom: 3px;
            right: 80px;
        }
    </style>
</head>

<body>
    <h3 class="heads">Edit Record</h3>
    <hr>

    <form method="post" action="">
        {% csrf_token %}
        <div class="form-group">
            <label for="complainee_fname">Complainee First name</label>
            {{form.complainee_fname}}

            <label for="complainee_fname">Complainee last name</label>
            {{form.complainee_lname}}

            <label for="complainee_fname">Complainee CNIC</label>
            {{form.complainee_cnic}}

            <label for="complainee_fname">Complainee contactNo</label>
            {{form.complainee_contactno}}

            <label for="complainee_fname">Email Address</label>
            {{form.email_address}}

            <label for="complainee_fname">crime description</label>
            {{form.crime_description}}

            <label for="complainee_fname">Victim description</label>
            {{form.victim_description}}

            <label for="complainee_fname">Date of complain</label>
            {{form.dateofcomplain}}

            <label for="complainee_fname">Time of complain </label>
            {{form.timeofcomplain}}

            {% if val %}
            <label for="complainee_fname">FIR status</label>

            {{form.FIR_status}}
            {%endif%}

            <button type="submit" class="btn btn-primary save">Save
                Changes</button>
        </div>

    </form>




</body>


</html>

djproject/templates/updaterecord.html
{%load widget_tweaks%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Record</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous">
    </script>



    <style>
        .form-group {
            position: absolute;

            display: inline-block;
            width: 411px;

            padding: 10px;
            left: 10%;
        }

        .heads {
            margin-top: 23px;
            margin-left: 20px;
            font-size: calc(1.3rem + .6vw);
        }

        button,
        input,
        optgroup,
        select,
        textarea {
            margin: 10px;
            width: 100%;
            border-radius: 4px;
            border: 1px solid black;
            font-family: monospace;
            font-size: 17px;
            display: flex;
            padding: 3px;
        }

        label {
            display: inline-block;
            font-weight: bold;
            font-size: 17px;
        }


        .btn-primary {
            color: #fff;
            width: 157px;
            font-size: 18px;
            position: absolute;
            bottom: -59px;
            font-family: system-ui;
            background-color: #0d6efd;
            border-color: #0d6efd;
        }


        #id_CaptureStatus {
            position: absolute;
            bottom: 3px;
            right: 42px;
        }

    </style>
</head>

<body>
    <h3 class="heads">Edit Record</h3>
    <hr>

    <form method="post" action="">
        <div class="form-group">
            {% csrf_token %}
            {{form}}
            

            <button type="submit" class="btn btn-primary save">Save
                Changes</button>
        </div>

    </form>




</body>


</html>